#!/usr/bin/env bash

## Code standards check
##
## Usage: fin cs

set -e

# Copy required files.
[ -f .phpcs.xml ] && echo "File .phpcs.xml exists." || cp .docksal/files/.phpcs.xml .

echo "Check coding standards:"
fin run-cli --image=$CLI_IMAGE --clean ./vendor/bin/phpcs

echo "Check code for deprecations:"
fin run-cli --image=$CLI_IMAGE --clean ./vendor/bin/drupal-check openy_gated_content

echo "Check JS application with linter"
cd "${PROJECT_ROOT}/openy_gated_content/js/gated-content"
fin exec npm install
fin exec npm run lint-no-fix
