#!/usr/bin/env bash

## Code standards check
##
## Usage: fin cs

set -e

cd "${PROJECT_ROOT}/openy_gated_content"
fin exec phpcs

cd "${PROJECT_ROOT}/openy_gated_content/js/gated-content"
fin exec npm install
fin exec npm run lint-no-fix
