version: "2.1"

services:
  cli:
    environment:
      # Pass additional variables (used in custom commands) from host to cli
      - SITE_DIRECTORY
      - SOURCE_ALIAS
      - VIRTUAL_HOST
  # Adminer
  adminer:
    hostname: adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db # db is the default database container
      - ADMINER_PLUGINS=tables-filter tinymce # To load Adminer plugins
      - ADMINER_DESIGN=price # To use a bundled Adminer design
    labels:
      - io.docksal.virtual-host=adminer.${VIRTUAL_HOST}
  # MailHog
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
